---
title: "Spotify Wrapped"
subtitle: "A Deep Dive into My Monthly Streaming"
author: "Matteo Torres"
date: "January 01, 2025"
execute: 
  output: false
format: 
  html:
    theme: darkly
    toc: true
editor_options: 
  chunk_output_type: console
---

## Load Packages
```{r}
#| code-fold: true

library(hms)
library(ggstar)
library(lubridate)
library(tidyverse)
library(googlesheets4)
```

## Read Data
```{r}
spotify_data_raw <- read_sheet("https://docs.google.com/spreadsheets/d/1U2XrypJcbxnK-hb4GnnqcOejY00HU1kcCVIfWHB_Q7A/edit?usp=sharing")
```

## Data Exploration
```{r, output = TRUE}
# Preview the raw data
head(spotify_data_raw, n = 5)
```

## Data Cleaning
```{r, output = TRUE}
# Create a function to tidy the Spotify dataset
spotify_data_processed <- function(spotify_data_raw) {
  
  # Save the original column names
  current_colnames <- colnames(spotify_data_raw)
  
  # Add the current column names as the first row
  spotify_data_raw <- rbind(current_colnames, spotify_data_raw)
  
  # Assign new, more descriptive column names
  new_colnames <- c("date", "track_name", "artist", "track_id", "link")
  colnames(spotify_data_raw) <- new_colnames
  
  # Clean the "date" column
  spotify_data_raw$date <- gsub(" at", "", spotify_data_raw$date)
  
  # Convert the "date" column to a proper date-time format
  spotify_data_raw$date <- mdy_hm(spotify_data_raw$date)
  
  # Convert the "track_name" column to a character type
  spotify_data_raw$track_name <- as.character(spotify_data_raw$track_name)
  
  # Return the cleaned and processed dataset
  return(spotify_data_raw)
}

# Apply the cleaning function to the raw dataset
spotify_data_clean <- spotify_data_processed(spotify_data_raw)

# Preview the cleaned dataset
head(spotify_data_clean, n = 5)
```

## Data Analysis
```{r}
# Create monthly datasets
monthly_datasets <- spotify_data_clean %>%
  mutate(ymd_date = as.Date(date),
         md_date = format(ymd_date, "%b %d"),
         month = month(date, label = TRUE),
         time = as_hms(date)) %>%
  group_by(month) %>%
  group_split()

# Month
i <- 1
```

### Top Artists
```{r, message  = TRUE}
#| code-fold: true

# Summarize the number of unique artists for the given month
u_artists <- monthly_datasets[[i]] %>%
  summarize(month = month[i], total_unique_artists = n_distinct(artist))

# Print a message with the total number of unique artists and the month
message(paste("You listened to", u_artists$total_unique_artists, "different artists in", u_artists$month, "!"))
```

```{r, output = TRUE}
#| code-fold: true

# Summarize the top 5 artists for the given month
top_5_artists <- monthly_datasets[[i]] %>%
  group_by(artist) %>%
  summarize(total_streams = sum(n())) %>%
  arrange(desc(total_streams)) %>%
  slice_head(n = 5)

# Create a bar plot for the top 5 artists
ggplot(data = top_5_artists, 
       aes(x = reorder(artist, total_streams), y = total_streams)) +
  geom_bar(stat = "identity", 
           fill = "#8ACE00") +
  geom_text(aes(label = total_streams), hjust = 1.5, family = "Courier") +
  labs(x = "",
       y = "Total Number of Streams (n)",
       title = paste("Top 5 Artists in", monthly_datasets[[i]]$month, "!")) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_bw() +
  theme(axis.text.x = element_text(family = "Courier"),
        axis.text.y = element_text(family = "Courier"),
        axis.title.x = element_text(family = "Courier"),
        axis.title.y = element_text(family = "Courier"),
        plot.title = element_text(family = "Courier", size = 14)) +
  coord_flip()
```

```{r, message = TRUE}
#| code-fold: true

# Summarize the most-streamed song by the top artist
top_artist_song <- inner_join(monthly_datasets[[i]], top_5_artists[1, 1:2], by = "artist") %>%
  group_by(track_name) %>%
  summarize(total_streams = sum(n())) %>%
  arrange(desc(total_streams)) %>%
  slice_head(n = 1)

# Print a message showing the most-streamed song by the top artist and its total streams
message(paste(top_artist_song$track_name, "is your most-played song by", top_5_artists$artist[1], ", with a total of", top_artist_song$total_streams, "streams !"))
```

### Top Songs
```{r, message = TRUE}
#| code-fold: true

# Print a message with the total number of track streams for the given month
message(paste("You listened to a total of", nrow(monthly_datasets[[i]]), "songs in", monthly_datasets[[i]]$month[1], "!"))
```

```{r, message  = TRUE}
#| code-fold: true

# Summarize the number of unique tracks for the given month
u_tracks <- monthly_datasets[[i]] %>%
  summarize(month = month[i], total_unique_tracks = n_distinct(track_name))

# Print a message with the total number of unique tracks and the month
message(paste("Out of those", nrow(monthly_datasets[[i]]), ",", u_tracks$total_unique_tracks, "were different songs !"))
```

```{r, output = TRUE}
#| code-fold: true

# Summarize the top 5 tracks for the given month
top_5_tracks <- monthly_datasets[[i]] %>%
  group_by(track_name) %>%
  summarize(total_streams = sum(n())) %>%
  arrange(desc(total_streams)) %>%
  slice_head(n = 5)

# Create a bar plot for the top 5 tracks
ggplot(data = top_5_tracks, 
       aes(x = reorder(track_name, total_streams), y = total_streams)) +
  geom_bar(stat = "identity", 
           fill = "#8ACE00") +
  geom_text(aes(label = total_streams), hjust = 2, family = "Courier") +
  labs(x = "",
       y = "Total Number of Streams (n)",
       title = paste("Top 5 Songs in", monthly_datasets[[i]]$month, "!")) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_bw() +
  theme(axis.text.x = element_text(family = "Courier"),  
        axis.text.y = element_text(family = "Courier"),
        axis.title.x = element_text(family = "Courier"),
        axis.title.y = element_text(family = "Courier"),
        plot.title = element_text(family = "Courier", size = 14)) +
  coord_flip()
```

### Streaming Habits
```{r, message = TRUE}
#| code-fold: true

# Summarize the number of songs streamed per day for the given month
daily_songs <- monthly_datasets[[i]] %>%
  group_by(ymd_date) %>%
  summarize(n_songs = n()) %>%
  mutate(md_date = format(ymd_date, "%b %d")) %>%
  arrange(desc(n_songs))

# Print a message for the highest streaming day
message(paste("Your highest streaming day was", daily_songs$md_date[1], "with", daily_songs$n_songs[1], "songs streamed !"))
```

```{r, message = TRUE}
#| code-fold: true

# Extract the last row of the dataframe (lowest streaming day)
lowest_streaming_day <- daily_songs %>% 
  slice_tail(n = 1)

# Print a message for the lowest streaming day
message(paste("Your lowest streaming day was", lowest_streaming_day$md_date, "with", lowest_streaming_day$n_songs, "songs streamed !"))
```

```{r, output = TRUE}
#| code-fold: true

# Create a line plot of daily streaming habits
ggplot(data = daily_songs, aes(x = ymd_date, y = n_songs)) +
  geom_point(color = "#8ACE00") +
  geom_line(color = "#8ACE00", linewidth = 1) +
  geom_star(data = daily_songs[1, ], fill = "black", size = 3) +
  labs(x = "Date",
       y = "Total Number of Streams (n)",
       title = paste("Monthly Streaming Habits for", monthly_datasets[[i]]$month, "!")) +
  scale_x_date(expand = c(0, 0), date_breaks = "2 days", date_labels = "%b %d") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, family = "Courier"),  
        axis.text.y = element_text(family = "Courier"),
        axis.title.x = element_text(family = "Courier"),
        axis.title.y = element_text(family = "Courier"),
        plot.title = element_text(family = "Courier", size = 14))
```

```{r, output = TRUE}
#| code-fold: true

# Extract the day with the highest streams
highest_streaming_day <- inner_join(monthly_datasets[[i]], daily_songs[1, 1:2], by = "ymd_date")

# Create a histogram of streaming times for the highest streaming day 
ggplot(data = highest_streaming_day, aes(x = time)) +
  geom_histogram(bins = 30, fill = "#8ACE00") +
  labs(x = "Time",
       y = "Total Number of Streams (n)",
       title = paste("Highest Streaming Day,", daily_songs$md_date[1], "!")) +
  scale_x_time(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, family = "Courier"),  
        axis.text.y = element_text(family = "Courier"),
        axis.title.x = element_text(family = "Courier"),
        axis.title.y = element_text(family = "Courier"),
        plot.title = element_text(family = "Courier", size = 14))
```

## Data Citations
| Data | Citation | Link |
|------|----------|------|
| Google Sheets | Torres, M. (2025). Spotify Wrapped 2025 [Google Sheets]. Google. | https://docs.google.com/spreadsheets/d/1U2XrypJcbxnK-hb4GnnqcOejY00HU1kcCVIfWHB_Q7A/edit?gid=0#gid=0 |
| My Spotify Wrapped | IFTTT. (n.d.). My Spotify Wrapped [Applet]. | https://ifttt.com/applets/ptQiGLyZ-my-spotify-wrapped |
| Spotify | Spotify. (n.d.). *Spotify* [Music streaming service] | https://www.spotify.com |

